### ISSUE TITLE
fix: update css class name

### ISSUE THREAD

**Issue by arkdeployer** [DVNCL/dvnc-theme#1]
https://github.com/DVNCL/dvnc-theme/blob/ca0a87445162a05f670e663c851ca0c0141e6621/src/styles/light.css#L1

The above line needs to be changed to `.theme-plugin-dvnc-mode {` to match the name in the index.js

https://github.com/DVNCL/dvnc-theme/blob/ca0a87445162a05f670e663c851ca0c0141e6621/src/index.js#L4

**Comment by DVNCL** [comment]
Fixed
